---
functional:
  - Сайт должен иметь удобную мобильную версию
  - Сайт должен быть доступен на различных устройствах
non-functional:
  - Сайт должен быть способен обрабатывать большое количество трафика (например, 1000 одновременных пользователей)
  - Сайт должен быть совместим с последними версиями браузеров
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен быть удобен в использовании и оптимизирован для скорости работы
implicit:
  - требование 5
  - требование 6
